---
title: "Oceanographic monitoring of the Gully MPA – A synopsis of data collected by the Atlantic Zone Monitoring Program"
year: 2021
report_number: 337
author: |
  Jeffrey W. Jackson^1^,
  Erica J. H. Head^1^,
  Lindsay I. Beazley^1^, and
  Andrew T. Cogswell^1^
author_list: "Jackson, J.W., Head, E.J.H., Beazley, L.I. and Cogswell, A.T."
region: Maritimes Region
isbn: "978-0-660-40625-1"
address: |
  ^1^Ocean and Ecosystem Sciences Division\
     Fisheries and Oceans Canada\
     Bedford Institute of Oceanography\
     P.O. Box 1006\
     Dartmouth, Nova Scotia\
     Canada, B2Y 4A2
phone: "(902) 426-2373"
author_footnote: "Email: Jeffrey.Jackson @ dfo-mpo.gc.ca"
abstract: |
  In 2004, the Gully was established as Atlantic Canada’s first Marine Protected Area (MPA) under Canada’s Oceans Act. While the oceanographic setting of the Gully MPA has been described, little has been done to assess changes in its physical, chemical, or biological properties, which is essential in evaluating whether the MPA is meeting its conservation objectives. Since the late 1990’s, the Atlantic Zone Monitoring Program (AZMP) has routinely collected hydrographic and biological data within the Gully MPA, although until now these data had not been examined in the context of environmental monitoring. Here, we present a compilation and reproducible analysis of oceanographic data collected at four fixed sampling stations in the Gully between 2000 and 2018. Temperature, salinity, oxygen, and nutrient and chlorophyll a concentrations were examined, as were wet weight biomass and abundance of the most common copepod taxa. Seasonal and inter-annual variability was high and few trends were observed, although mid-depth temperatures showed increasing trends at all stations. The main goal of this report is to provide operational advice for effective monitoring of the Gully’s oceanographic properties, with a focus on identifying redundancies or gaps in the AZMP’s existing monitoring strategy. We also provide a preliminary assessment of the MPA’s oceanographic environmental monitoring indicators.
abstract_other: |
  En 2004, le Gully a été établi comme première zone de protection marine (ZPM) du Canada atlantique en vertu de la Loi sur les océans du Canada. Bien que le milieu océanographique de la ZPM du Gully ait été décrit, peu de choses ont été faites pour évaluer les changements dans ses propriétés physiques, chimiques ou biologiques, ce qui est essentiel pour déterminer si la ZPM atteint ses objectifs de conservation. Depuis la fin des années 1990, le Programme de monitorage de la zone Atlantique (PMZA) recueille régulièrement des données hydrographiques et biologiques dans la ZPM du Gully, bien que ces données n’aient pas encore été examinées dans le contexte de la surveillance environnementale. Nous présentons ici une compilation et une analyse reproductible des données océanographiques recueillies à quatre stations d’échantillonnage fixes dans le Gully entre 2000 et 2018. La température, la salinité, l’oxygène ainsi que les concentrations d’éléments nutritifs et de chlorophylle ont été examinés, tout comme le poids humide de la biomasse et l’abondance des taxons copépodes les plus communs. La variabilité saisonnière et interannuelle était élevée et peu de tendances ont été observées, bien que les températures à mi-profondeur aient montré des tendances à la hausse à toutes les stations. Le principal objectif de ce rapport est de fournir des conseils opérationnels pour assurer une surveillance efficace des propriétés océanographiques du Gully, en mettant l’accent sur le recensement des redondances et des lacunes dans la stratégie de surveillance existante du PMZA. Nous fournissons également une évaluation préliminaire des indicateurs de surveillance de l’environnement océanographique de la ZPM.
output:
 csasdown::techreport_pdf:
   french: false
   copy_sty: false
   line_nums: false
   line_nums_mod: 1
   lot_lof: true
   latex_engine: xelatex
type:
  techreport
# ------------
# End of options to set
knit: bookdown::render_book
site: bookdown::bookdown_site
link-citations: true
bibliography: bib/refs.bib
lot: true
lof: true
# Any extra LaTeX code for the header:
header-includes:
 - \usepackage{float} \usepackage{xfrac} \usepackage{gensymb} \usepackage{multirow} \usepackage{colortbl} \usepackage{xcolor} \usepackage{bookmark} \usepackage{mathptmx} 

---

```{r setup, echo=FALSE, cache=FALSE, message=FALSE, results='hide', warning=FALSE}
library(knitr)
if (is_latex_output()) {
  knitr_figs_dir <- "knitr-figs-pdf/"
  knitr_cache_dir <- "knitr-cache-pdf/"
  fig_out_type <- "png"
} else {
  knitr_figs_dir <- "knitr-figs-docx/"
  knitr_cache_dir <- "knitr-cache-docx/"
  fig_out_type <- "png"
}
fig_asp <- 0.618
fig_width <- 9
fig_out_width <- "6in"
fig_dpi <- 180
fig_align <- "center"
fig_pos <- "htb"
opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  message = FALSE,
  comment = "#>",
  fig.path = knitr_figs_dir,
  cache.path = knitr_cache_dir,
  fig.asp = fig_asp,
  fig.width = fig_width,
  out.width = fig_out_width,
  echo = FALSE,
  #  autodep = TRUE,
  #  cache = TRUE,
  cache.comments = FALSE,
  dev = fig_out_type,
  dpi = fig_dpi,
  fig.align = fig_align,
  fig.pos = fig_pos
)
options(xtable.comment = FALSE)
options(kableExtra.latex.load_packages = FALSE)
```

```{r load-libraries, cache=FALSE}
# `french` and `prepub` variables are extracted from the YAML headers above and
#  are used throughout the document. To make the document all in french, change
#  the line in the YAML header above to `french: true`
meta <- rmarkdown::metadata$output
if(length(grep("pdf", names(meta)))){
  french <- meta$`csasdown::techreport_pdf`$french
  prepub <- meta$`csasdown::techreport_pdf`$prepub
}else if(length(grep("word", names(meta)))){
  french <- meta$`csasdown::techreport_word`$french
  prepub <- meta$`csasdown::techreport_word`$prepub
}
csl <- "csl/csas.csl"
if(french){
  csl <- "csl/csas-french.csl"
  options(OutDec =  ",")
}

# add other packages here:
library(plyr)
library(dplyr)
library(ggplot2)
library(readr)
library(rosettafish)
library(tibble)
library(remotes)
library(csasdown)
library(kableExtra)
library(lubridate)
library(readxl)
library(tidyr)
library(scales)
library(stringi)
library(stringr)
library(oce)
library(fs)
library(tidyverse)
library(cowplot)
library(egg)
library(ggpubr)
library(pracma)
library(ggthemes)

```

---
csl: `r csl`    
---
